language: node_js
sudo: false
repo_token: w7s1sn1VhLBeuySISWn3Np2dkQ2D92N41

node_js:
  - 0.11

before_install:
  - npm install -g gulp
  - npm install -g bower
  - bower install

script:
  - gulp coveralls
