language: node_js
sudo: false

node_js:
  - 0.11

install:
  - npm install -g gulp
  - npm install -g bower

before_script:
  - bower install

branches:
  only:
  - master

env:
  - TASK=tests
  - TASK=coveralls

git:
  depth: 5

matrix:
  allow_failures:
    - env: "TASK=coveralls"

script:
  - gulp $TASK

addons:
  sauce_connect:
    username: "reflectiv"
    access_key:
      secure: "brnH8iNtopeteMze9l6oApK9eoIc6EjqcaJcKJknlifEryWLUwRUsm3zi63bVvFOEATuhy82TkkDo57x2COpJbJ0+WqgkDS+Cl90MpQvuEiFj3S0huYjMc8mO9ZxS26wf+waWF+XWoyqvfesOHYwEzRXIw34WoSEhK3Y+9/1sc8="
