language: node_js
sudo: false

node_js:
  - 0.11

before_install:
  - npm install -g gulp
  - npm install -g bower
  - bower install

script:
  - sc -u "reflectiv" -k "15210a5c-e40b-4d9a-89b9-c0936d2f56fb" —doctor
  - sc -u "reflectiv" -k "15210a5c-e40b-4d9a-89b9-c0936d2f56fb" -vv mylog.txt
  - cat mylog.txt
  - gulp coveralls

addons:
  sauce_connect:
    username: "reflectiv"
    access_key:
      secure: "brnH8iNtopeteMze9l6oApK9eoIc6EjqcaJcKJknlifEryWLUwRUsm3zi63bVvFOEATuhy82TkkDo57x2COpJbJ0+WqgkDS+Cl90MpQvuEiFj3S0huYjMc8mO9ZxS26wf+waWF+XWoyqvfesOHYwEzRXIw34WoSEhK3Y+9/1sc8="
